title: dash v.1
email: geireann_lindfield_roberts@brown.edu
description: >- # this means to ignore newlines until "baseurl:"
  This is the official documentation for dash, a hypermedia system built and run by the Pen and Touch Graphics Lab at Brown University. 

color_scheme: dash
# Local Setting
baseurl: ""
url: ""

# Theme
theme: "just-the-docs"
# remote_theme: pmarsceill/just-the-docs